### ISSUE TITLE
Uncaught TypeError: todos.map is not a function

### ISSUE THREAD

**Issue by divRobles** [jphafelin/Todolist-Application-Using-React#2]
## Observaciones 🧐
> - Aparte, cuando lo abro se rompe. Me sale el error: `Uncaught TypeError: todos.map is not a function`. Esto ocurre porque tu estado empieza estando vacío y por lo tanto no puede hacerle el `map`. Te paso un `snapshot` del código con eso corregido (línea 65). Básicamente le introduzco un condicional que establece que haga el `map` solo si la longitud de `todos` es mayor que 0. Si tienes alguna duda me dices 🙂

[snapshot código corregido](https://gitpod.io#snapshot/65dfdf03-7d74-412b-8b0d-cb9129d5d55c)

**Comment by jphafelin** [comment]
Hola Jesús:

En primer lugar, gracias por la corrección de lo del map. Lo del PUT y
DELETE no está hecho porque esta entrega es la primera, que no lleva fetch.
Es por eso que no lo tengo. El GET está hecho porque utilicé el mismo
código para hacer el proyecto que sí lleva fetch.

Un saludo!
